// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK51XXUtNb5VHVWB1gMAbS5YZVe95MuuY',
    appId: '1:980794846647:web:7e1efed69075039e4b0c32',
    messagingSenderId: '980794846647',
    projectId: 'maximize-b376c',
    authDomain: 'maximize-b376c.firebaseapp.com',
    storageBucket: 'maximize-b376c.firebasestorage.app',
    measurementId: 'G-ZLNHXWKDGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC89BtP1Kch89me5jz9ZaV0eOgHPa0FTGQ',
    appId: '1:980794846647:android:7319fcda04d1e7664b0c32',
    messagingSenderId: '980794846647',
    projectId: 'maximize-b376c',
    storageBucket: 'maximize-b376c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhZ7chHl3xX01_FwErVY5OnsaZbG9HUE',
    appId: '1:980794846647:ios:74cc565ef652674b4b0c32',
    messagingSenderId: '980794846647',
    projectId: 'maximize-b376c',
    storageBucket: 'maximize-b376c.firebasestorage.app',
    iosBundleId: 'com.example.maximize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYhZ7chHl3xX01_FwErVY5OnsaZbG9HUE',
    appId: '1:980794846647:ios:74cc565ef652674b4b0c32',
    messagingSenderId: '980794846647',
    projectId: 'maximize-b376c',
    storageBucket: 'maximize-b376c.firebasestorage.app',
    iosBundleId: 'com.example.maximize',
  );
}
